<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StockPilot.DataAccessLayer\StockPilot.DataAccessLayer.csproj" />
    <ProjectReference Include="..\StockPilot.EntityLayer\StockPilot.EntityLayer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
